### ISSUE TITLE
DEFAULT_PAGE_SIZE = 1000 instead of 100,000 as stated in docs

### ISSUE THREAD

**Issue by bryanbarnard** [FlipsideCrypto/sdk#13]
DEFAULT_PAGE_SIZE = 1000, this used to be 100,000 differs from documentation stating that default page size is 100,000.
This requires users of the SDK that were regularly returning more than 1000 records to update every query they run when adopting the new version of the SDK.

https://github.com/FlipsideCrypto/sdk/blob/aafde1bc6a118e31bd90a8900f13c4eb8b3b9376/python/src/flipside.py#L19

### Docs
https://docs.flipsidecrypto.com/flipside-api/get-started/python

![CleanShot 2023-05-05 at 10 11 09](https://user-images.githubusercontent.com/972181/236522786-8658b967-0344-470e-9360-3c8a752af79a.png)

**Comment by jfmyers** [comment]
Hi, @bryanbarnard thanks for raising this. This should now be resolved in v2.0.4.

Please note: the server permits a max page size of 30MB. If 100k rows exceed 30MB an error will be returned and a max page size will be suggested given the average byte size of each row.

**Comment by bryanbarnard** [comment]
@jfmyers noted regarding 30MB limit. Thanks for the quick turnaround on this fix.
