### ISSUE TITLE
QUERY_RUN_EXECUTION_ERROR: SQL compilation error: Missing column specification

### ISSUE THREAD

**Issue by dahifi** [FlipsideCrypto/sdk#22]
Python SDK: 2.0.7

Query works great on xyz studio app and has been working fine up until today: 
```
  SELECT RECORDED_HOUR, MAX(CLOSE)
    FROM solana.core.fact_token_prices_hourly
    WHERE symbol = 'ATLAS'
    AND RECORDED_HOUR > '{timestamp}'::timestamp without time zone
    GROUP BY RECORDED_HOUR
    ORDER BY RECORDED_HOUR
```
We'd been using the FS SDK, 2.0.3, for last week or two and had no problems up till yesterday, everything broke this morning.

**Comment by bryanbarnard** [comment]
+1

**Comment by jfmyers** [comment]
Thanks, @dahifi @bryanbarnard, we're taking a look.

**Comment by jfmyers** [comment]
This issue has been resolved. The problem originated in our API from an update around how result sets are exported once you execute the query. Please let us know if the issue persists. Thanks!

**Comment by bryanbarnard** [comment]
Thanks @jfmyers. This fixed the issue I was seeing with my SQL including comments, but a later issue popped up where my sql that previously did timestamp comparison using formats like YYYY-MM-DD HH:MM:SS stopped working and was throwing a strange sql compilation error, saying unexpected ';'.

I was able to resolve this by updating my queries to use a different format (YYYY-MM-DD HH:MM:SS.ms)

Thanks for looking into these issues!
