### ISSUE TITLE
Pydantic pinned to buggy version, breaking compatibility with another package

### ISSUE THREAD

**Issue by scottincrypto** [FlipsideCrypto/sdk#23]
A bug (https://github.com/pydantic/pydantic/issues/5821) in pydantic==1.10.7 has been fixed in pydantic==1.10.8

The flipside python API is pinned to pydantic==1.10.7.  Another package I'm using is pinning around pydantic==1.10.7 to avoid the referenced bug.

Suggest relaxing the pydantic to maintain compatibility, thanks.

**Comment by watsy0007** [comment]
I have the same problem.
