### ISSUE TITLE
JS/TS SDK Doesn't Work with Cloudflare Workers

### ISSUE THREAD

**Issue by chand1012** [FlipsideCrypto/sdk#32]
When used inside a Cloudflare Worker, this is the error message that appears:
```
Error: UNEXPECTED_SDK_ERROR: adapter is not a function
```

Which according to [this StackOverflow post](https://stackoverflow.com/a/70206333), is probably due to Axios not recognizing the environment its in and using the wrong code to try and execute the request.

Until this is fixed I'll be using the RPC API directly with `fetch`.

**Comment by jfmyers** [comment]
Thanks for the PR. Merged and released as version 2.1.0: https://www.npmjs.com/package/@flipsidecrypto/sdk
